In [1]:
import yaml
import os
os.chdir('C:\\Users\\401738\\Downloads\\ipl\\')

FUNCTION to load each YAML files for a particular IPL season. #start and #end variables are the starting and ending file names 

In [2]:
def load_data(start , end ):
    matches = []
    for i in range(start, end):
        if os.path.isfile('./'+str(i)+'.yaml'):
            with open('./'+str(i)+'.yaml','r')as f:
                doc= yaml.load(f)
                matches.append(doc)
    return matches
    

Calling the above function and passing the start and end file names to load the data.

In [3]:
m_2008 = load_data(335982,336041)

In [4]:
m_2009 = load_data(392181,392240 )

In [5]:
m_2010 = load_data(419106,419166)

In [6]:
m_2011 = load_data(501198, 501272)

In [7]:
m_2012 = load_data(548306, 548382)

In [8]:
m_2013 = load_data(597998, 598074)

In [9]:
m_2014 = load_data(729279, 734050)

In [10]:
m_2015 = load_data(829705, 829824)

In [11]:
m_2016 = load_data(980901, 981020)

In [12]:
m_2017 = load_data(1082591, 1082651)

The following function extracts important information from each match of a season,viz runs per over , wickets per over and total runs in each innings in the form of a DICTIONARY object. You need to only pass the innings dict.

In [13]:
def extract_data(innings):
    total_runs =0
    k=0.0
    prev=0.0
    over_runs = {}
    over_wickets = {}
    runs= 0
    w_counter = 0
    for i in range(0,len(innings)):
        #if (i==0):
            #print ('Match Started: Over # 1')
        for k , v in innings[i].items():
            if ((prev//1) != (k//1)):
                #print ('Over #', int((prev//1) +1),' completed')
                #print ('Runs Scored #',runs)
                runs+= int(innings[i][k]['runs']['total'])
                if ('wicket' in innings[i][k]):
                    w_counter+=1
                    over_wickets[k] = [w_counter,innings[i][k]['wicket']['player_out'],innings[i][k]['wicket']['kind']]
                    #print (' Over -', k,'Out!!','wicket #',w_counter, innings[i][k]['wicket']['player_out'],innings[i][k]['wicket']['kind'])
                over_runs[int((prev//1) +1)]= int(runs)
                #print ('Over #', int((k//1) +1),' started and running')
                runs = 0
            else:
                #print ('Over #', int((prev//1) +1),' running')
                runs+= int(innings[i][k]['runs']['total'])
                if ('wicket' in innings[i][k]):
                    w_counter+=1
                    over_wickets[k] = [w_counter,innings[i][k]['wicket']['player_out'],innings[i][k]['wicket']['kind']]
                    #rint (' Over -', k,'Out!!','wicket #',w_counter, innings[i][k]['wicket']['player_out'],innings[i][k]['wicket']['kind'])
            prev = k
            total_runs+= innings[i][k]['runs']['total']
        if( i == len(innings) -1 ):
            #print ('Over #', int((prev//1) +1),' completed')
            #print ('Runs Scored #',runs)
            over_runs[int((prev//1) +1)]= int(runs)
    return over_runs , over_wickets , total_runs

This function wraps the DICTIONARY objects created by the above function for a match and stores the same for all the matches in a season into a LIST object.

In [14]:
def generate_data(matches):
    rpo_innings1 = []
    rpo_innings2 = []
    wpo_innings1 = []
    wpo_innings2 = []
    tr_innings1 = []
    tr_innings2 = []
    team_innings1 = []
    team_innings2 = []
    misc_info = []
    
    for i in range(0,len(matches)):
        
        if (len(matches[i]['innings']) > 1):
            
            rpo_i1 , wpo_i1 , tr_i1 = extract_data(matches[i]['innings'][0]['1st innings']['deliveries'])
            rpo_innings1.append(rpo_i1)
            wpo_innings1.append(wpo_i1)
            tr_innings1.append(tr_i1)
            team_innings1.append(matches[i]['innings'][0]['1st innings']['team'])
        
            rpo_i2 , wpo_i2 , tr_i2 = extract_data(matches[i]['innings'][1]['2nd innings']['deliveries'])
            rpo_innings2.append(rpo_i2)
            wpo_innings2.append(wpo_i2)
            tr_innings2.append(tr_i2)
            team_innings2.append(matches[i]['innings'][1]['2nd innings']['team'])
           
            
            misc_info.append([matches[i]['info']['venue'],matches[i]['info']['toss']['winner'],matches[i]['info']['toss']['decision'],matches[i]['info']['outcome']])
        else :
            pass
            
    return rpo_innings1, rpo_innings2 , wpo_innings1 , wpo_innings2 , tr_innings1, tr_innings2, team_innings1 , team_innings2,misc_info

Calling the above function and creating a series of LIST objects.

In [15]:
rpo_i1_2008,rpo_i2_2008,wpo_i1_2008,wpo_i2_2008,tr_i1_2008,tr_i2_2008,team_i1_2008,team_i2_2008,misc_info_2008 = generate_data(m_2008)
rpo_i1_2009,rpo_i2_2009,wpo_i1_2009,wpo_i2_2009,tr_i1_2009,tr_i2_2009,team_i1_2009,team_i2_2009,misc_info_2009 = generate_data(m_2009)
rpo_i1_2010,rpo_i2_2010,wpo_i1_2010,wpo_i2_2010,tr_i1_2010,tr_i2_2010,team_i1_2010,team_i2_2010,misc_info_2010 = generate_data(m_2010)
rpo_i1_2011,rpo_i2_2011,wpo_i1_2011,wpo_i2_2011,tr_i1_2011,tr_i2_2011,team_i1_2011,team_i2_2011,misc_info_2011 = generate_data(m_2011)
rpo_i1_2012,rpo_i2_2012,wpo_i1_2012,wpo_i2_2012,tr_i1_2012,tr_i2_2012,team_i1_2012,team_i2_2012,misc_info_2012 = generate_data(m_2012)
rpo_i1_2013,rpo_i2_2013,wpo_i1_2013,wpo_i2_2013,tr_i1_2013,tr_i2_2013,team_i1_2013,team_i2_2013,misc_info_2013 = generate_data(m_2013)
rpo_i1_2014,rpo_i2_2014,wpo_i1_2014,wpo_i2_2014,tr_i1_2014,tr_i2_2014,team_i1_2014,team_i2_2014,misc_info_2014 = generate_data(m_2014)
rpo_i1_2015,rpo_i2_2015,wpo_i1_2015,wpo_i2_2015,tr_i1_2015,tr_i2_2015,team_i1_2015,team_i2_2015,misc_info_2015 = generate_data(m_2015)
rpo_i1_2016,rpo_i2_2016,wpo_i1_2016,wpo_i2_2016,tr_i1_2016,tr_i2_2016,team_i1_2016,team_i2_2016,misc_info_2016 = generate_data(m_2016)
rpo_i1_2017,rpo_i2_2017,wpo_i1_2017,wpo_i2_2017,tr_i1_2017,tr_i2_2017,team_i1_2017,team_i2_2017,misc_info_2017 = generate_data(m_2017)

In [16]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model 

This function takes wickets per over dictionary created earlier, and returns the total wickets that has fallen during a match for a particular team.

In [17]:
def add_wpo(wpo):  
    wickets= []
    for i in range(len(wpo)):
        wickets.append([(int(k//1) + 1) for k, v in wpo[i].items()])
    wickets_full=[]
    for li in wickets:
        wickets_full.append([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
        for i in li:
            if i in range(1,21):
                wickets_full[wickets.index(li)][i-1] += 1 
    return wickets_full

This function below creates a full Dataset combining all the above extracted information on an innings level.

In [18]:
def create_full_dataset(rpo_inn, tr_inn , wpo_inn):
    rpo_inn_df = pd.DataFrame.from_dict(rpo_inn)
    tr_inn_df = pd.DataFrame(tr_inn, columns =['Total'])
    w_inn_df = pd.DataFrame([len(i) for i in wpo_inn], columns = ['wickets'])
    runs_wickets_inn_df = w_inn_df.join(tr_inn_df)

    wickets_full = add_wpo(wpo_inn)
    wickets_df = pd.DataFrame(wickets_full,columns=['wickts_1','wickts_2','wickts_3','wickts_4','wickts_5','wickts_6',
                     'wickts_7','wickts_8','wickts_9','wickts_10','wickts_11','wickts_12','wickts_13','wickts_14',
                     'wickts_15','wickts_16','wickts_17','wickts_18','wickts_19','wickts_20'])
    inn_df = rpo_inn_df.join(wickets_df)
    inn_df = inn_df.join(runs_wickets_inn_df)
    inn_df.columns = ['runs_1','runs_2','runs_3','runs_4','runs_5','runs_6','runs_7','runs_8','runs_9','runs_10','runs_11','runs_12',
                     'runs_13','runs_14','runs_15','runs_16','runs_17','runs_18','runs_19','runs_20','wickts_1','wickts_2',
                     'wickts_3','wickts_4','wickts_5','wickts_6','wickts_7','wickts_8','wickts_9','wickts_10','wickts_11',
                     'wickts_12','wickts_13','wickts_14','wickts_15','wickts_16','wickts_17','wickts_18','wickts_19','wickts_20',
                     'wickets','Total']
    return inn_df

In [19]:
i1_df = create_full_dataset(rpo_i2_2012, tr_i2_2012, wpo_i2_2012)


In [20]:
misc_df = pd.DataFrame(misc_info_2008, columns =['venue','toss_winner','toss_decision','match_winner'])


In [21]:
scaler = StandardScaler()

In [22]:
print (len(m_2008),len(m_2009),len(m_2010),len(m_2011),len(m_2012),len(m_2013),len(m_2014),len(m_2015),len(m_2016),len(m_2017))

58 57 60 73 74 76 60 59 60 59


In [23]:
y_train = i1_df['Total'][0:40]

In [24]:
y_test = i1_df['Total'][41:74]

In [151]:
i1_df=i1_df.drop(['runs_7','runs_8','runs_9','runs_10','runs_11','runs_12',
                     'runs_13','runs_14','runs_15','runs_16','runs_17','runs_18','runs_19','runs_20','wickts_7','wickts_8','wickts_9','wickts_10','wickts_11',
                     'wickts_12','wickts_13','wickts_14','wickts_15','wickts_16','wickts_17','wickts_18','wickts_19','wickts_20',
                     'wickets','Total'], axis=1)

In [25]:
x_train = i1_df[0:40]

In [26]:
x_test = i1_df[41:74]

In [27]:
x_train = x_train.fillna(0)

In [28]:
x_test = x_test.fillna(0)

In [29]:
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
x_train= scaler.transform(x_train)

In [31]:
x_test = scaler.transform(x_test)

In [32]:
scaler.inverse_transform(x_test)

array([[   5.,   10.,   14., ...,    0.,    4.,  144.],
       [  12.,    9.,    7., ...,    0.,    6.,  163.],
       [   6.,    7.,    6., ...,    0.,    6.,  119.],
       ..., 
       [   7.,   17.,    7., ...,    1.,    9.,  149.],
       [   7.,   10.,    5., ...,    0.,   10.,  136.],
       [   3.,    7.,   10., ...,    0.,    5.,  192.]])

In [33]:
scaler2 = StandardScaler()
scaler2.fit(y_train)

C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\preprocessing\data.py:586: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [34]:
y_train = scaler2.transform(y_train)

C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


In [35]:
y_test = scaler2.transform(y_test)

C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
C:\Continuum\Anaconda2\envs\TFENV\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


In [36]:
scaler2.inverse_transform(y_test)

array([ 144.,  163.,  119.,  150.,  143.,  134.,  174.,  185.,  154.,
        126.,  145.,  142.,  127.,  138.,  155.,  115.,  125.,  194.,
        173.,  160.,  140.,  108.,  123.,  194.,  128.,  145.,  102.,
        123.,  163.,  144.,  149.,  136.,  192.])

In [37]:
reg = linear_model.Ridge(alpha= .9)

In [181]:
from sklearn.decomposition import PCA

In [182]:
p = PCA(n_components = 2)

In [188]:
p.fit(x_train.T)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [189]:
x_train_new = p.components_

In [38]:
reg.fit(x_train,y_train)

Ridge(alpha=0.9, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [40]:
y_pred = reg.predict(x_test)

In [41]:
scaler2.inverse_transform(y_pred)

array([ 141.29632681,  157.6016125 ,  120.78512697,  148.74103693,
        139.11911903,  138.89741282,  171.23521683,  185.40427587,
        159.12609394,  122.16799209,  145.13902621,  139.68902215,
        130.22822947,  137.53364879,  156.65785718,  116.18106806,
        121.87718932,  192.86061009,  166.38972559,  155.19740605,
        135.16478717,  113.14151342,  123.11501252,  190.75254659,
        130.33536351,  150.72617534,  104.80437467,  128.49835882,
        165.33781178,  143.07718656,  142.45009346,  135.90851336,
        193.81579109])

In [42]:
reg.score(x_test,y_test)

0.97778247650942163